### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by Creatz** [stouch/directus-interface-uuid-file-image#1]
First of all, congratulations and thanks for the work done, nevertheless, I can't execute the build command

npx directus-extension build :
```
Error: Could not resolve './directus/app/src/utils/get-root-path' from src/interface.vue?vue&type=script&lang.ts
Error: Could not resolve './directus/app/src/utils/get-root-path' from src/interface.vue?vue&type=script&lang.ts
    at error (/Users/name/Desktop/directus-interface-uuid-file-image-main/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/Users/name/Desktop/directus-interface-uuid-file-image-main/node_modules/rollup/dist/shared/rollup.js:22336:24)
    at /Users/name/Desktop/directus-interface-uuid-file-image-main/node_modules/rollup/dist/shared/rollup.js:22310:26
```

**Comment by bnznt** [comment]
It failed at `postinstall` script. You can run that script manually. But there is another way to get it work.

1. Create a file called `get-root-path.ts` in `src` folder with the following content:
```javascript
export function getRootPath(): string {
	const path = window.location.pathname;
	const parts = path.split('/');
	const adminIndex = parts.indexOf('admin');
	const rootPath = parts.slice(0, adminIndex).join('/') + '/';
	return rootPath;
}

export function getPublicURL(): string {
	const path = window.location.href;
	const parts = path.split('/');
	const adminIndex = parts.indexOf('admin');
	const rootPath = parts.slice(0, adminIndex).join('/') + '/';
	return rootPath;
}
```

2. Then open `src/interface.vue` and replace [this line](https://github.com/stouch/directus-interface-uuid-file-image/blob/main/src/interface.vue#L60) with `import { getRootPath } from './get-root-path'`

3. Run `npx directus-extension build` again and you ready to go 🚀

By the way, thank @stouch for writing this extension. It saved my day.

**Comment by Creatz** [comment]
Thank you very much for your answer, 
It works perfectly!

**Comment by buzzeins** [comment]
Just opened a pull request https://github.com/stouch/directus-interface-uuid-file-image/pull/4/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519 with that solution in. 
Also updated deps and removed unnecessary postinstall script. Maybe @stouch can review and merge it?

**Comment by stouch** [comment]
Thanks @buzzeins !  I merged it :+1:
